name: Release
on:
  push:
    branches:
      - 'release'
permissions:
  contents: write
  actions: read
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - uses: arduino/setup-task@v2
      - name: Display Go version
        run: go version
      - name: Display Go mod tidy
        run: go mod tidy
      - name: Build binaries for mac
        run: task release
      - name: Generate checksums
        run: task sha
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./.release/mission-darwin-amd64
            ./.release/mission-darwin-amd64.sha256
            ./.release/mission-darwin-arm64
            ./.release/mission-darwin-arm64.sha256
          draft: false
          prerelease: false
          generate_release_notes: true
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
